### ISSUE TITLE
Module build failed: Error: ENOENT: no such file or directory, open 'E:\raja\emoji\node_modules\ng2-emojify\index.js.map'

### ISSUE THREAD

**Issue by sekharbuchi** [sauravgaursmith/ng2-emojify#1]
I don,t know why this error came?

**Comment by sauravgaursmith** [comment]
Hi Sekharbuchi, I will definitely will look into it and will let you know the solution soon...

**Comment by sauravgaursmith** [comment]
Hi I will surely look into it.

**Comment by sekharbuchi** [comment]
k... thanks

*--*
*Thanks & Regards*

*Rajasekhar Buchi,*
*Application Developer,*
*Genems Systems Pvt.Ltd,*
*+91 9052587461*

**Comment by sauravgaursmith** [comment]
Hi, 
You need to compile code into javascript (es5) with source map true option. Look into tsconfig.json in the module and set configuration according to your need. Although, we have never face this issue. If you still facing this issue please send a basic portion of your file where you are using this.
